GET http://localhost:4000/recipes


###

GET http://localhost:4000/recipes/616b16b828a1234014179223

###

POST http://localhost:4000/recipes
Content-Type: application/json

{
    "name":"Gnocchi de batata",
    "score":3,
    "steps":["pisar batatas","mezclar harina"],
    "ingredients":[{"name":"batata","unitShare": 2}]
}

###

DELETE http://localhost:4000/recipes/616b1ea5d060ec2cc800534a

###

PUT http://localhost:4000/recipes/616b1e61d060ec2cc8005344
Content-Type: application/json

{
    "name":"Arroz con Pollo",
    "score":4.3,
    "steps":["picar cebolla","cortar tomates"],
    "ingredients":[{"name": "cebolla", "unitShare": 0.125},{ "name": "tomate", "unitShare": 0.25 }]
}